FROM ruby:3.2-bookworm

WORKDIR /app

# Install system dependencies
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      build-essential \
      curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs 4 --retry 3

# Copy app
COPY . .

CMD ["bundle", "exec", "rackup", "-o", "0.0.0.0", "-p", "4567", "sinatra/config.ru"]